### PR TITLE
Add support for Service Role

### LINKED ISSUE #30: Is it possible to use client with `service_role`?
In one of  my projects I use custom composable for Supabase and now I want to migrate it to `supabase-module`. In the project I have an API request on Nuxt server side which use `service_role` to bypass RLS. I need to update the place where authorized user doesn't have access (it's read-only for them) and the update is based on external request called on server side. 

I wonder if it's possible to use `useSupabaseClient()`, in this case, with `service_role` secret key instead of `public` anon key. Of course only on server side in this specific place.

### PR DESCRIPTION
**Pull request by lukaszflorczak**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

It adds a new composable (`useSupabaseService()`) that allows using service role (service role key has the ability to bypass Row Level Security) on the server-side.

Resolves #30.

## Use case example

Imagine that you want to create your own user verification system where the user has to put in the confirmation code. Your Supabase client (created by `useSupabaseClient`) shouldn't have access to that code in your database. When the user puts the code on the client-side it should be compared in secret with the code in the database. This is the place where you can use server API offered by Nuxt 3 and `useSupabaseServiceRole` composable:

```ts [pages/verification.vue]
const code = ref(null) // Form input v-model
const user = useSupabaseUser()

const onSubmit = async () => {
  const isVerified = await $fetch('/api/verification', { method: 'POST', body: { code: code.value, userId: user.value.id } })
}
```

```ts [server/api/verification.ts]
export default defineEventHandler(async (event) => {
  const client = useSupabaseServiceRole()
  const { code, userId } = await useBody(event)
  
  const { data: { verificationCode } } = await client.from('codes').select().eq('userId', userId).single()
  
  return { isVerified: code === verificationCode }
})
```

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by larbish** [comment]
PR looks good but can you provide a use case ?

**Comment by lukaszflorczak** [comment]
Hey. I updated the description, documentation and added a use case

**Comment by larbish** [comment]
Thank you very much for the work you've done ! I think we should call this composable `useSupabaseServiceRole`, it is more understandable. Also I think the doc part should be in the `usage` section in order to keep a quick overview of all composables in this part.

Concerning the use case, did you try it ? Because I think you're facing this issue #27. I have planned to talk about it later this week with @Atinux  in order to find a way to use composables inside server routes. 

Also, we should update the doc and the use case to avoid using the [legacy syntax](https://v3.nuxtjs.org/guide/features/server-routes/#return-a-legacy-handler-or-middleware) of server routes. We should use `defineEventHandler ` instead.

**Comment by lukaszflorczak** [comment]
> I think we should call this composable `useSupabaseServiceRole`, it is more understandable. Also I think the doc part should be in the `usage` section in order to keep a quick overview of all composables in this part.

I agree. Done ✅

> Concerning the use case, did you try it ? Because I think you're facing this issue #27.

You are right. I refactored the composable and it works now. But the biggest problem is we don't have access to `useRuntimeConfig()` so we have to based on `.env` directly. I'm very curious if this could be solved in a better way... 🤔
 
> Also, we should update the doc and the use case to avoid using the [legacy syntax](https://v3.nuxtjs.org/guide/features/server-routes/#return-a-legacy-handler-or-middleware) of server routes. We should use `defineEventHandler ` instead.

Done ✅

**Comment by larbish** [comment]
Thanks for the update ! I'll get in touch with the framework team to know if we can find a way to use composables on server side (using nitro). Concerning the update you made on `useSupabaseServiceRole`, we should never cache a variable globally otherwise it will be shared across requests. I'll come back to you quickly to propose something consistent 🙂

**Comment by lukaszflorczak** [comment]
> I'll get in touch with the framework team to know if we can find a way to use composables on server side (using nitro)

Hey @larbish! Do yo have any update?

**Comment by larbish** [comment]
Hi @lukaszflorczak, I have a pending branch supporting "composables", named "services" on server routes. There is one last error I need to fix, the framework team should come back to me with a solution. You can have a look at the [PR](https://github.com/nuxt-community/supabase-module/pull/35/files). I'll keep you in touch !

**Comment by larbish** [comment]
Hey @lukaszflorczak, I don't know what happens with your pull request. However, I finally managed to add support for the supabase utilities in the server routes. You can check the PR here: https://github.com/nuxt-community/supabase-module/pull/36/files. Hope it helps to achieve what you wanted to do: create a `serverSupabaseServiceRole` available in server routes.

Let me know if you need helps on anything 🙂

**Comment by lukaszflorczak** [comment]
I'm not sure what happened and where my changes went. I'll check the PR you mentioned soon.

**Pull request merged**
